# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "i915" ];
  boot.kernelParams = [
    "i915.enable_psr=0"
    "i915.enable_dc=0"       # Disables Power Saving Display C-states
    "i915.enable_fbc=0"      # Disables Framebuffer Compression
    "i915.mitigations=off"   # (Optional) Small boost by disabling CPU security mitigations
  ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3575c709-53ed-47ef-aed3-c21a4429650c";
      fsType = "ext4";
    };

  fileSystems."/mnt/md127" =
    { device = "/dev/disk/by-id/ata-TOSHIBA_MQ01ABD075_8318P8C2T-part2";
      options = [ "noatime" ];
      fsType = "ext4";
    };
  fileSystems."/mnt/windows" =
    { device = "/dev/disk/by-id/ata-TOSHIBA_MQ01ABD075_8318P8C2T-part1";
      fsType = "ntfs-3g"; 
      options = [ "rw" "uid=1000"];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/57A8-4BD6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [
    {
      device = "/mnt/md127/swapfile";
      size = 8 * 1024;
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
