
windowrule {
    name = appblocker
    match:class = ^(appblocker-overlay)$
    float = on
    no_anim = on
    no_focus = on
    pin = on
    border_size = 0
    opacity = 1.0 override 1.0 override
}