#!/usr/bin/env python
## nix-shell -i python3 -p gobject-introspection vte "python3.withPackages(ps: [ ps.pygobject3 ])"

import gi
import os
import i3
import sys
gi.require_version("Gdk", "3.0")
from gi.repository import Gdk
import warnings
warnings.filterwarnings("ignore")

disp = Gdk.Display.get_default()
scr = disp.get_default_screen()
win_pos = scr.get_active_window().get_origin()
# print("win: %d x %d" % (win_pos.x, win_pos.y))
monitor = disp.get_monitor_at_point(win_pos.x, win_pos.y)
rect = monitor.get_geometry()
is_primary = monitor.is_primary();
screen = 0 if is_primary else 1
x = rect.x
y = rect.y
width = rect.width
height = rect.height
i3.msg("command","[class=\"SpeedCrunch\"] scratchpad show, move position center, move right %d px" % ((width / 2 - 150)))
# i3.move("position center",title="SpeedCrunch")
# i3.move("right %d px" % ((width / 2 - 150)),title="SpeedCrunch");
