# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ata_piix" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-intel" "vfio-pci" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "usbhid.mousepoll=1" "intel_iommu=on" "mitigations=off" ];


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/80c83225-edcc-4f2e-84f8-ebbe5b892a95";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9EE8-9678";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  environment.systemPackages = [ pkgs.rclone ];
  environment.etc."rclone-mnt.conf".text = ''
  [myremote]
  type = sftp
  host = 192.168.1.203
  user = andrew
  key_file = /home/andrew/.ssh/id_rsa
'';

  # fileSystems."/mnt/pc" = {
  #   device = "andrew@192.168.1.203:/";
  #   fsType = "sshfs";
  #   options = [
  #     "nodev"
  #     "noatime"
  #     "allow_other"
  #     "IdentityFile=/home/andrew/.ssh/id_rsa"
  #   ];
  # };

  fileSystems."/mnt/pc" = {
    device = "myremote:/";
    fsType = "rclone";
    options = [
      "nodev"
      "nofail"
      "allow_other"
      "args2env"
      "config=/etc/rclone-mnt.conf"
      
      # --- PERFORMANCE TWEAKS ---
      # 1. Enable Full VFS Cache. This makes it feel like a local disk.
      # It caches reads/writes to /var/cache/rclone (default) or a path you set.
      "vfs-cache-mode=full"
      
      # 2. Tune directory listing speed vs. freshness.
      # If you want to see changes made ON THE REMOTE faster, lower this.
      # 10s is a good balance for local networks.
      "dir-cache-time=10s"
      
      # 3. Increase lookahead and buffer for smoother file access.
      "vfs-read-ahead=128M"
      "buffer-size=64M"
      
      # 4. Use more parallel connections for transfers (SFTP specific)
      "transfers=8"
    ];
  };

  fileSystems."/mnt/yandex" = lib.mkIf (builtins.pathExists "/home/andrew/Dropbox/rclone/rclone.conf") {
    device = "yad:/";
    fsType = "rclone";
    options = [
      "nodev"
      "nofail"
      "allow_other"
      "args2env"
      "config=/home/andrew/Dropbox/rclone/rclone.conf"
    ];
  };

  fileSystems."/mnt/gdrive" = lib.mkIf (builtins.pathExists "/home/andrew/Dropbox/rclone/rclone.conf") {
    device = "gdrive:/";
    fsType = "rclone";
    options = [
      "nodev"
      "nofail"
      "allow_other"
      "args2env"
      "config=/home/andrew/Dropbox/rclone/rclone.conf"
    ];
  };


  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
